---
- name: Install NopCommerce 
  become: yes  
  hosts: ubuntu
  tasks:
    - name: Install dotnet 7
      ansible.builtin.apt:
        name: "{{ dotnet }}"
        update_cache: yes   
        state: present 

    - name: Create group
      ansible.builtin.group:
        name: "{{ group }}"
        state: present
    
    - name: Create user
      ansible.builtin.user:
        name: "{{ user }}"
        group: "{{ group }}"
        create_home: true
        home: "{{ home_dir }}"

    - name: Download NopCommerce 
      ansible.builtin.get_url:
        url: "{{ nop_url }}"
        dest: "{{ home_dir }}"
 
    - name: Install unzip
      ansible.builtin.apt:
        name: unzip
        update_cache: yes   
        state: present 
    
    - name: Unzip NopCommerce 
      ansible.builtin.unarchive:
        src: "{{ home_dir }}/{{ zip_url }}"
        dest: "{{ home_dir }}"
        remote_src: yes
    
    - name: Create bin and logs folder
      ansible.builtin.file:
        path: 
          - "{{ home_dir }}/bin"
          - "{{ home_dir }}/logs"
        state: directory

    - name: Give full permissions 
      ansible.builtin.file:
        path: "{{ home_dir }}"
        owner: "{{ user }}"
        group: "{{ group }}"
        mode: "0777"
        state: directory
        recurse: yes

    - name: Copy nop.service file
      ansible.builtin.copy:
        src: nop.service
        dest: /etc/systemd/system/nop.service

    - name: Enable and start nop.service
      ansible.builtin.service:
        name: nop
        enabled: yes
        state: started
    
