---
- name: Install NopCommerce 
  become: yes  
  hosts: ubuntu
  tasks:
    - name: Install dotnet 7
      ansible.builtin.apt:
        name: "{{ dotnet }}"
        update_cache: yes   
        state: present 