---
- name: Install NopCommerce 
  become: yes  
  hosts: ubuntu
  tasks:
    - name: Install dotnet 7
      ansible.builtin.apt:
        name: "{{ dotnet }}"
        update_cache: yes   
        state: present 

    - name: Create group
      ansible.builtin.group:
        name: "{{ group }}"
        state: present
    
    - name: Create user
      ansible.builtin.user:
        name: "{{ user }}"
        group: "{{ group }}"
        create_home: true
        home: "{{ home_dir }}"
        