---
- name: Install NopCommerce 
  become: yes  
  hosts: ubuntu
  roles:
    - nop
    - geerlingguy.mysql
  vars: 
    mysql_user_name: sujata
    mysql_user_password: sujata 
    mysql_bind_address: 0.0.0.0