---
- name: install nginx server
  hosts: all
  become: true 
  tasks:
    - name: install nginx
      ansible.builtin.apt:
        name: nginx
        update_cache: yes
        state: present 