---
- name: install lamp server
  hosts: all
  become: true
  vars:
    info_page: /var/www/html/info.php
  tasks:
    - name: install apache
      ansible.builtin.package:
        name: "{{ package_name}}"
        update_cache: yes   
        state: present
    
    - name: enable apache
      ansible.builtin.systemd:
        name: "{{ package_name}}"
        enabled: true
        state: started
        
    - name: install php packages
      ansible.builtin.package:
        name: "{{ item }}"          
        update_cache: yes
        state: present
      loop: "{{ php_packages }}"
      notify: restart apache

    - name: copy info.php
      ansible.builtin.copy:
        src: info.php
        dest: "{{ info_page }}"
      notify: restart apache

  handlers:
    - name: restart apache
      ansible.builtin.systemd:
        name: "{{ package_name}}"
        state: restarted
   