---
- name: install lamp server
  hosts: ubuntu
  become: true
  tasks:
    - name: install apache2 in ubuntu
      ansible.builtin.apt:
        name: apache2
        update_cache: yes   
        state: present
      when: ansible_facts['distribution'] == 'Ubuntu'
    - name: install php packages in ubuntu
      ansible.builtin.apt:
        name:
          - php
          - libapache2-mod-php
          - php-mysql  
        update_cache: yes
        state: present
      notify: restart apache
      when: ansible_facts['distribution'] == 'Ubuntu'
    - name: copy info.php in ubuntu
      ansible.builtin.copy:
        src: info.php
        dest: /var/www/html/info.php
      notify: restart apache
      when: ansible_facts['distribution'] == 'Ubuntu'
    - name: install httpd in Centos
      ansible.builtin.yum:
        name: httpd
        state: present
      when: ansible_facts['distribution'] == 'CentOS'
    - name: enable httpd
      ansible.builtin.systemd:
        name: httpd
        enabled: true
        state: started
      when: ansible_facts['distribution'] == 'CentOS'
    - name: install php in Centos
      ansible.builtin.yum:
        name: php
        state: present
      notify: restart httpd
      when: ansible_facts['distribution'] == 'CentOS'
    - name: copy info.php in Centos
      ansible.builtin.copy:
        src: info.php
        dest: /var/www/html/info.php
      notify: restart httpd
      when: ansible_facts['distribution'] == 'CentOS'
  handlers:
    - name: restart apache
      ansible.builtin.systemd:
        name: apache2
        state: restarted
    - name: restart httpd
      ansible.builtin.systemd:
        name: httpd
        state: restarted